name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/build


